name: download image from BING
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'
    - name: Download image
      run: |
        python update_profile.py
        
    - name: Commit files
      run: |
         git config --local user.email "2476618387@qq.com"
         git config --local user.name "yanhaolin"
         git add bing_img.png
         git commit -m "update readme.md"
    - name: Push changes
      uses:  makerlin1/makerlin1@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
